import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { auth } from "@/auth";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import LoginButon from "@/components/ui/local/LoginButton";
import SignOutButton from "@/components/ui/local/SignOutButton";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}
      >
        <nav className="flex w-full justify-between items-center p-1 sm:p-2 md:p-4">
          <nav>
            <Link href="/">
              <Button variant="link">Home</Button>
            </Link>
            <Link href="/journal">
              <Button variant="link">Journal</Button>
            </Link>
            {session?.user.role === "ADMIN" && (
              <Link href="/admin">
                <Button variant="link">Admin</Button>
              </Link>
            )}
          </nav>
          {session ? (
            <>
              <SignOutButton link={session.user?.image || "null"} />
            </>
          ) : (
            <LoginButon />
          )}
        </nav>
        <div className="p-4 h-full bg-red-500">{children}</div>
      </body>
    </html>
  );
}
