import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { auth } from "@/auth";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import LoginButon from "@/components/ui/local/LoginButton";
import SignOutButton from "@/components/ui/local/SignOutButton";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex w-full justify-between items-center p-4">
          <Link href="/">
            <Button variant="link">Home</Button>
          </Link>
          {session ? (
            <>
              <SignOutButton link={session.user?.image || "null"} />
            </>
          ) : (
            <LoginButon />
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
